#!/usr/bin/env python3
"""
gen_ts_types.py — 由规范1的机器可读 schema 生成前端 TS 枚举类型片段（非阻断）。

唯一来源：docs/standards/db_schema_spec.json（规范1 db_schema_spec）。
默认 dry-run：只打印到 stdout，不写盘、不连网、不连 DB、退出码恒 0。
加 --write 才落盘到 app/lib/generated_enums.ts（新文件，绝不覆盖 app/lib/supabase.ts）。

用法：
    python3 cloud/gen_ts_types.py            # 预览
    python3 cloud/gen_ts_types.py --write    # 写入 app/lib/generated_enums.ts
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "docs" / "standards" / "db_schema_spec.json"
OUT = ROOT / "app" / "lib" / "generated_enums.ts"

# JSON 字段名 -> TS 类型名（仅餐厅主表枚举；其余表按需扩展）
TYPE_NAME = {
    "chain_type": "ChainType",
    "central_kitchen": "CentralKitchen",
    "premade_risk": "PremadeRisk",
    "food_safety": "FoodSafety",
    "price_position": "PricePosition",
    "status": "RestaurantStatus",
}


def to_ts_union(values: list[str]) -> str:
    return " | ".join(f"'{v}'" for v in values)


def build_snippet(spec: dict) -> str:
    restaurants = spec.get("tables", {}).get("restaurants", {})
    enums = restaurants.get("enums", {})
    lines = [
        "// AUTO-GENERATED by cloud/gen_ts_types.py from docs/standards/db_schema_spec.json",
        "// DO NOT hand-edit. 改枚举 -> 改 JSON + 重跑脚本。",
        "",
    ]
    for field, values in enums.items():
        tname = TYPE_NAME.get(field)
        if not tname:
            continue  # 未登记的枚举先跳过，不臆造类型名
        lines.append(f"export type {tname} = {to_ts_union(values)};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    write = "--write" in sys.argv
    spec = json.loads(SPEC.read_text(encoding="utf-8"))
    snippet = build_snippet(spec)

    if write:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(snippet, encoding="utf-8")
        print(f"[gen_ts_types] wrote {OUT.relative_to(ROOT)}")
    else:
        print(snippet)
        print(f"[gen_ts_types] dry-run only; re-run with --write to emit {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
