#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""写入 raw_poi_new.jsonl：6 家经多源核实的新发现店（只产 raw，不写库）。"""
import json, pathlib

HERE = pathlib.Path(__file__).resolve().parent
TODAY = "2026-09-24"

records = [
    # ---------------- 1. nagi (Nagi 凪) —— 回归点名店 ----------------
    {
        "name": "nagi 凪",
        "name_en": "Nagi",
        "brand_group": None,
        "brand_confirmed": False,
        "scene": "正餐",
        "cuisine_paths": [["亚洲菜", "日料", "Omakase板前"]],
        "form": "Finedining",
        "meals": ["晚餐"],
        "ingredients": ["海鲜", "肉禽"],
        "price_avg": 1680,
        "price_range": "午市/晚市套餐同价 约¥1680（有食客记¥2280档）",
        "price_sources": [
            {"platform": "抖音", "value": 1680, "url": "https://www.iesdouyin.com/share/video/7620293479381986121"},
            {"platform": "Trip.com", "value": None, "url": "https://hk.trip.com/restaurant/china/shanghai/detail/restaurant-153463185/"},
        ],
        "district": "浦东新区",
        "address": "上海市浦东新区陆家嘴滨江大道1368号1层01室",
        "business_area": "陆家嘴/滨江",
        "lat": 31.243866, "lng": 121.526513,
        "coord_source": "tencent",
        "phone_raw": "15026966118",
        "booking_method": "电话预约（板前9席，极难订，食客称提前2-3个月）",
        "signature_dishes": ["现拆红毛蟹·马蹄", "缟鲹叶烧", "桜鳟炭烧", "烤目光鱼", "荧光鱿鱼", "Toris无花果提拉米苏千层"],
        "status": "open",
        "scores": {"objective": 62, "diner": 82, "taste": 80, "endorsement": 55, "soft_ad_penalty": 8, "platform_credibility": 0.8},
        "evidence": {
            "diner_quotes": [
                {"quote": "江师傅發揮穩定啊，現拆紅毛蟹過於美味了，每一道都能感受到滿滿的誠意，手藝人即視感", "dish": "红毛蟹", "source": "Trip.com", "url": "https://hk.trip.com/restaurant/china/shanghai/detail/restaurant-153463185/", "date": "2026-07-17"},
                {"quote": "江師傅在板前拆紅毛蟹，今天的菜單：紅毛蟹·馬蹄、烏賊·里芋、縞鯵·葉燒、桜鳟·炭燒……新店沒有包廂只有板前9個位置", "dish": "红毛蟹·马蹄", "source": "抖音", "url": "https://www.iesdouyin.com/share/video/7507566119331728699", "date": "2025-05-23"},
                {"quote": "烤物依舊是目光魚和熒光魷魚，nagi就是有能力把烤目光魚做的比其他家好吃，極致的細嫩軟滑，非常的香", "dish": "烤目光鱼", "source": "抖音", "url": "https://www.iesdouyin.com/share/video/7642421810725803099", "date": "2026-05-22"},
            ],
            "platform_scores": [
                {"platform": "Trip.com", "score": 4.6, "review_count": 5, "url": "https://hk.trip.com/restaurant/china/shanghai/detail/restaurant-153463185/"},
            ],
            "negative_signals": ["座位仅9席极难订，有食客反映等位3个月以上"],
            "soft_ad_flags": ["抖音探店密度高（'上海最难约'叙事集中）"],
            "traffic_signals": ["食客称需提前2-3个月预约", "板前9席满座"],
        },
        "sources": [
            {"title": "Trip.com: Nagi 凪 商户页", "url": "https://hk.trip.com/restaurant/china/shanghai/detail/restaurant-153463185/", "type": "platform"},
            {"title": "抖音：江师傅的料理美学 #凪nagi", "url": "https://www.iesdouyin.com/share/video/7507566119331728699", "type": "ugc"},
            {"title": "携程笔记：这才是一饭封神 依然是上海最难约的", "url": "https://m.ctrip.com/webapp/you/community/detail?articleId=352231552", "type": "ugc"},
        ],
        "data_updated_at": TODAY,
        "notes": "发现路径：腾讯 suggestion('Nagi 凪')未召回→web 检索 Trip.com 商户页+抖音多源锁定→腾讯 geocoder 补坐标。⚠️身份存疑：本店为江师傅主理的浦东板前 omakase，与东京『すごい煮干ラーメン凪』拉面连锁非同一业态；官网 n-nagi.com 海外店清单未列上海，品牌关系未证实，brand_confirmed=false。电话为 Trip.com 登记手机号。",
    },
    # ---------------- 2. 鮨·天照 —— 回归点名店“鮨照” ----------------
    {
        "name": "鮨·天照 Omakase(南京西路店)",
        "name_en": None,
        "brand_group": None,
        "brand_confirmed": False,
        "scene": "正餐",
        "cuisine_paths": [["亚洲菜", "日料", "Omakase板前"]],
        "form": "Finedining",
        "meals": ["午餐", "晚餐"],
        "ingredients": ["海鲜"],
        "price_avg": 669,
        "price_range": "约¥669（另有¥980套餐档）",
        "price_sources": [
            {"platform": "高德(POI)", "value": 669, "url": None},
        ],
        "district": "静安区",
        "address": "上海市静安区静安寺威海路500号丰盛商业中心一层R1-01",
        "business_area": "南京西路/丰盛里",
        "lat": 31.227086, "lng": 121.462008,
        "coord_source": "tencent",
        "phone_raw": None,
        "booking_method": "到店/电话（POI未返回电话）",
        "signature_dishes": ["雪花鹅肝海胆金枪鱼", "冰淇淋鹅肝", "河豚白子", "十年绍兴酒牡丹虾", "鲍鱼雪花盐"],
        "status": "open",
        "scores": {"objective": 60, "diner": 68, "taste": 66, "endorsement": 40, "soft_ad_penalty": 10, "platform_credibility": 0.78},
        "evidence": {
            "diner_quotes": [
                {"quote": "冰淇淋鹅肝：全場最佳！主廚現場把鵝肝研磨成細膩的粉末，入口是冰淇淋般的質感，鹹鮮和奶香交織……河豚白子：入口即化，細膩醇厚", "dish": "冰淇淋鹅肝", "source": "携程笔记", "url": "https://m.ctrip.com/webapp/you/community/detail?articleId=372267337", "date": "2026-09-11"},
                {"quote": "招牌金槍魚紫膽鵝肝堪稱一絕，綿密鵝肝搭配鮮甜海膽與醇厚金槍，油脂香氣在口中緩緩化開，層次超豐富", "dish": "雪花鹅肝海胆金枪鱼", "source": "携程笔记", "url": "https://m.ctrip.com/webapp/you/community/detail?articleId=315896715", "date": "2026-06-02"},
                {"quote": "雪花鵝肝海膽金槍魚層次豐富，十年紹興酒牡丹蝦金燦燦酒醉，鹹鮮入口軟軟糯糯", "dish": "牡丹虾", "source": "穷游", "url": "https://m.qyer.com/feeds/p/ZFBfBSftnGq-e9AsD2DHQA.html", "date": "2026-09-10"},
            ],
            "platform_scores": [
                {"platform": "高德", "score": 4.5, "review_count": None, "url": None},
            ],
            "negative_signals": ["新店营销笔记密度较高，'炒鸡好吃'类话术集中"],
            "soft_ad_flags": ["携程/穷游探店笔记批量出现，鹅肝刨粉为统一传播点"],
            "traffic_signals": [],
        },
        "sources": [
            {"title": "腾讯地图 POI: 鮨·天照", "url": "https://apis.map.qq.com/", "type": "map"},
            {"title": "携程笔记：南京西路炒鸡好吃的omakase", "url": "https://m.ctrip.com/webapp/you/community/detail?articleId=372267337", "type": "ugc"},
            {"title": "穷游：被这家omakase征服啦", "url": "https://m.qyer.com/feeds/p/ZFBfBSftnGq-e9AsD2DHQA.html", "type": "ugc"},
        ],
        "data_updated_at": TODAY,
        "notes": "发现路径：腾讯 suggestion('鮨 天照')直接命中 POI（静安区威海路500号）。⚠️用户所称'鮨照'在地图册登记名为『鮨·天照』，未发现别名仅为'鮨照'的独立店铺；若用户另指他店需补充线索。",
    },
    # ---------------- 3. Hulu Sushi 葫芦寿司 ----------------
    {
        "name": "Hulu Sushi 葫芦寿司",
        "name_en": "Hulu Sushi",
        "brand_group": None,
        "brand_confirmed": False,
        "scene": "正餐",
        "cuisine_paths": [["亚洲菜", "日料", "Omakase板前"]],
        "form": "Finedining",
        "meals": ["晚餐"],
        "ingredients": ["海鲜"],
        "price_avg": 1080,
        "price_range": "Omakase 约¥1080/位",
        "price_sources": [
            {"platform": "Nomfluence", "value": 1080, "url": "https://rachelgouk.com/best-japanese-omakase-restaurants-in-shanghai/"},
        ],
        "district": "长宁区",
        "address": "上海市长宁区幸福路110号101单元（Pirata 内）",
        "business_area": "幸福路/武康路",
        "lat": 31.204982, "lng": 121.431349,
        "coord_source": "tencent",
        "phone_raw": None,
        "booking_method": "预订制（12席板前）",
        "signature_dishes": ["炙烤 Toro 配海胆", "海老扇贝海胆组合", "松茸蟹茶碗蒸"],
        "status": "open",
        "scores": {"objective": 58, "diner": 64, "taste": 70, "endorsement": 60, "soft_ad_penalty": 4, "platform_credibility": 0.82},
        "evidence": {
            "diner_quotes": [
                {"quote": "12-seat omakase tucked inside Pirata on Xingfu Road, chef-owner Liu-San is a seven-year veteran of Sushi Oyama; expect torched toro crowned with uni and layered ebi-scallop-sea urchin combinations", "dish": "炙烤Toro配海胆", "source": "Washoku Guide", "url": "https://washoku-guide.com/cities/shanghai/sushi", "date": "2026-05-19"},
                {"quote": "Chawanmushi with matsutake and crab; Omakase at Hulu Sushi is ¥1,080 per person", "dish": "松茸蟹茶碗蒸", "source": "Nomfluence", "url": "https://rachelgouk.com/best-japanese-omakase-restaurants-in-shanghai/", "date": "2026-06-03"},
            ],
            "platform_scores": [],
            "negative_signals": [],
            "soft_ad_flags": [],
            "traffic_signals": ["12席小体量，藏在 Pirata 内，靠海外美食媒体口碑"],
        },
        "sources": [
            {"title": "Washoku Guide: Authentic Sushi Shanghai", "url": "https://washoku-guide.com/cities/shanghai/sushi", "type": "overseas_media"},
            {"title": "Nomfluence: Best Japanese Omakase in Shanghai 2026", "url": "https://rachelgouk.com/best-japanese-omakase-restaurants-in-shanghai/", "type": "overseas_media"},
            {"title": "腾讯地图 POI", "url": "https://apis.map.qq.com/", "type": "map"},
        ],
        "data_updated_at": TODAY,
        "notes": "发现路径：腾讯 suggestion('板前 omakase')召回。主厨 Liu-San 出自 Sushi Oyama（7年），藏于 Pirata 店内。电话待补。",
    },
    # ---------------- 4. TEN HASU 天妇罗专门 ----------------
    {
        "name": "TEN HASU 天妇罗专门",
        "name_en": "TEN HASU",
        "brand_group": None,
        "brand_confirmed": False,
        "scene": "正餐",
        "cuisine_paths": [["亚洲菜", "日料", "天妇罗"]],
        "form": "Finedining",
        "meals": ["午餐", "晚餐"],
        "ingredients": ["海鲜", "蔬菜素食"],
        "price_avg": None,
        "price_range": "天妇罗 omakase 套餐（人均待补）",
        "price_sources": [],
        "district": "长宁区",
        "address": "上海市长宁区黄金城道810-2号（古北）",
        "business_area": "古北/黄金城道",
        "lat": 31.195078, "lng": 121.396588,
        "coord_source": "tencent",
        "phone_raw": None,
        "booking_method": "建议提前订位（板前+包厢）",
        "signature_dishes": ["海胆紫苏天妇罗", "和牛海胆天妇罗", "星鳗天妇罗", "𬶮鱼(しんじょ)天妇罗", "舞茸天妇罗", "甘鲷立鳞烧"],
        "status": "open",
        "scores": {"objective": 60, "diner": 70, "taste": 72, "endorsement": 45, "soft_ad_penalty": 6, "platform_credibility": 0.8},
        "evidence": {
            "diner_quotes": [
                {"quote": "海膽紫蘇天婦羅絕對封神，薄如蟬翼的面衣脆到咔嚓響，裡面海膽綿密得像雲朵化開", "dish": "海胆紫苏天妇罗", "source": "携程笔记", "url": "https://m.ctrip.com/webapp/you/community/detail?articleId=293432987", "date": "2026-04-16"},
                {"quote": "套餐包含和牛、星鳗、𬶮鱼、贝柱、虾头、虾身、太刀鱼、舞茸等8荤3素；外壳酥脆，咬开保留汁水", "dish": "和牛/星鳗天妇罗", "source": "携程笔记", "url": "https://m.ctrip.com/webapp/you/community/detail?articleId=241184329", "date": "2025-12-14"},
                {"quote": "和牛海膽天婦羅尤為驚艷，脂香鮮味裹挾酥脆外殼；收尾一碗天妇罗盖饭", "dish": "和牛海胆天妇罗", "source": "携程笔记", "url": "https://m.ctrip.com/webapp/you/community/detail?articleId=353236409", "date": "2026-08-09"},
            ],
            "platform_scores": [],
            "negative_signals": [],
            "soft_ad_flags": ["携程笔记数量偏多，存在模板化'咔嚓'文案"],
            "traffic_signals": ["食客称生意好需提前订位"],
        },
        "sources": [
            {"title": "携程笔记：古北天妇罗专门店初体验", "url": "https://m.ctrip.com/webapp/you/community/detail?articleId=293432987", "type": "ugc"},
            {"title": "携程笔记：上海古北天妇罗omakase我只服这家", "url": "https://m.ctrip.com/webapp/you/community/detail?articleId=360839396", "type": "ugc"},
            {"title": "腾讯地图 POI", "url": "https://apis.map.qq.com/", "type": "map"},
        ],
        "data_updated_at": TODAY,
        "notes": "发现路径：腾讯 suggestion('天妇罗 专门店')召回。古北板前天妇罗专门店，人均/电话待补。",
    },
    # ---------------- 5. 隅木食物所 ----------------
    {
        "name": "隅木食物所·台湾红烧牛肉面·台式小火锅(上生新所店)",
        "name_en": None,
        "brand_group": None,
        "brand_confirmed": False,
        "scene": "正餐",
        "cuisine_paths": [["中餐", "台湾菜"]],
        "form": "快餐简餐",
        "meals": ["午餐", "晚餐"],
        "ingredients": ["面", "肉禽"],
        "price_avg": None,
        "price_range": "台式面馆（人均待补）",
        "price_sources": [],
        "district": "长宁区",
        "address": "上海市长宁区新华路平武路80号101（上生新所旁，大树下）",
        "business_area": "上生新所/新华路",
        "lat": 31.208669, "lng": 121.431185,
        "coord_source": "tencent",
        "phone_raw": None,
        "booking_method": "无需预订",
        "signature_dishes": ["红烧沙茶牛肉面", "柠檬藤椒牛肉面", "麻锅牛肉面", "盐酥鸡", "麻辣鸭血豆腐", "嫩牛葱油拌面"],
        "status": "open",
        "scores": {"objective": 62, "diner": 72, "taste": 68, "endorsement": 48, "soft_ad_penalty": 4, "platform_credibility": 0.82},
        "evidence": {
            "diner_quotes": [
                {"quote": "红烧沙茶面，牛肉量不少、面筋道，汤头鲜美，里面还有两个Q弹鱼丸；柠檬藤椒牛肉面红汤里放柠檬，酸酸带鲜", "dish": "红烧沙茶牛肉面", "source": "携程笔记", "url": "https://m.ctrip.com/webapp/you/community/detail?articleId=305231900", "date": "2026-05-10"},
                {"quote": "招牌麻锅牛肉面放了好多块牛肉，厚实软嫩不柴，手工面条劲道弹牙，汤底微微辣", "dish": "麻锅牛肉面", "source": "携程笔记", "url": "https://m.ctrip.com/webapp/you/community/detail?articleId=280991803", "date": "2026-03-19"},
                {"quote": "面条很有劲道，汤底微微辣，牛筋牛肉酥烂入味，面条可以免费续", "dish": "红烧牛肉面", "source": "携程笔记", "url": "https://m.ctrip.com/webapp/you/community/detail?articleId=354596824", "date": "2026-08-11"},
            ],
            "platform_scores": [],
            "negative_signals": [],
            "soft_ad_flags": [],
            "traffic_signals": ["《承欢记》取景地（许凯同款）带来打卡客流"],
        },
        "sources": [
            {"title": "携程笔记：藏着红烧牛肉面一绝", "url": "https://m.ctrip.com/webapp/you/community/detail?articleId=305231900", "type": "ugc"},
            {"title": "今日头条：平武路上的隅木食物所", "url": "http://m.toutiao.com/group/7126198332694888994/", "type": "media"},
            {"title": "腾讯地图 POI", "url": "https://apis.map.qq.com/", "type": "map"},
        ],
        "data_updated_at": TODAY,
        "notes": "发现路径：腾讯 suggestion('台湾菜 牛肉面')召回。社区台式面馆，人均/电话待补。",
    },
    # ---------------- 6. 欢桃餐酒馆 ----------------
    {
        "name": "欢桃餐酒馆 Eatery & Bistro",
        "name_en": None,
        "brand_group": None,
        "brand_confirmed": False,
        "scene": "Bistro餐酒",
        "cuisine_paths": [["场景", "Bistro餐酒"], ["西餐", "融合菜"]],
        "form": "Bistro",
        "meals": ["晚餐", "夜宵"],
        "ingredients": ["海鲜", "肉禽"],
        "price_avg": None,
        "price_range": "融合 Bistro（人均待补）",
        "price_sources": [],
        "district": "静安区",
        "address": "上海市静安区静安寺永源路146号",
        "business_area": "永源路/静安寺",
        "lat": 31.220292, "lng": 121.439208,
        "coord_source": "tencent",
        "phone_raw": None,
        "booking_method": "无需预订/可排队",
        "signature_dishes": ["白烧鳝丝上海菜饭", "海鲜炖蛋(梭子蟹海胆花螺黑虎虾)", "黄油烤鸡佐菌菇土豆泥", "啵叽海鲜年糕", "鱼子酱配带子", "黑松露薯条"],
        "status": "open",
        "scores": {"objective": 60, "diner": 68, "taste": 66, "endorsement": 50, "soft_ad_penalty": 6, "platform_credibility": 0.8},
        "evidence": {
            "diner_quotes": [
                {"quote": "白烧鳝丝上海菜饭，鳝鱼鲜甜滑嫩，五常大米吸饱咸肉油脂，白胡椒微辛；海鲜炖蛋里藏着梭子蟹、海胆、花螺、黑虎虾", "dish": "白烧鳝丝上海菜饭", "source": "抖音", "url": "https://www.iesdouyin.com/share/video/7609969212152417536", "date": "2026-02-23"},
                {"quote": "黄油烤鸡佐菌菇土豆泥必点，土豆泥细腻绵密奶香十足；啵叽海鲜年糕让北京朋友折服", "dish": "黄油烤鸡", "source": "抖音", "url": "https://www.iesdouyin.com/share/video/7572136045501289034", "date": "2025-11-13"},
                {"quote": "鱼子酱配带子口感清新，带子肉质丰厚但配了柑橘香的醋，调味蛮日式", "dish": "鱼子酱配带子", "source": "抖音", "url": "https://www.iesdouyin.com/share/video/7149210841580145928", "date": "2022-10-02"},
            ],
            "platform_scores": [],
            "negative_signals": ["多年老店，高峰期需等位/偶遇名人"],
            "soft_ad_flags": [],
            "traffic_signals": ["食客称常偶遇李诞等文化名人，永源路bistro代表"],
        },
        "sources": [
            {"title": "抖音：永源街区3.0时代Bistro", "url": "https://www.iesdouyin.com/share/video/7609969212152417536", "type": "ugc"},
            {"title": "抖音：中西融合Bistro可刷菜单", "url": "https://www.iesdouyin.com/share/video/7572136045501289034", "type": "ugc"},
            {"title": "腾讯地图 POI", "url": "https://apis.map.qq.com/", "type": "map"},
        ],
        "data_updated_at": TODAY,
        "notes": "发现路径：腾讯 suggestion('bistro 餐酒馆')召回。永源路老牌融合 Bistro，人均/电话待补。",
    },
]

out = HERE / "raw_poi_new.jsonl"
with out.open("w", encoding="utf-8") as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")
print(f"wrote {len(records)} records -> {out}")
